#!/usr/bin/expect

# Very basic test script. Ensures that the program opens in a timely manner 
# and echoes entered text.

set timeout 5

spawn "./em9" test/1.txt

expect {
  timeout {
    close
    exit 1
  }
  "Col 1" {
    send_user "Successful first draw\n"
    send "line 1\r"
    send "line 2\r"
    send "\r"
    send "\r"
    send "unicode string λ"
  }
}

expect {
  "unicode string λ" {
    send_user "\nEntered string echoed\n"
    # Ctrl+s
    send "\x13"
    sleep .1
    # Ctrl+q
    send "\x11"
  }
}