#!/usr/bin/expect

# Very basic test script. Ensures that the program opens in a timely manner 
# and echoes entered text.

set timeout 1

spawn "./em9" README.md

send "my test string"

expect {
  timeout {
    close
    exit 1
  }
  "my test string" {
    # Ctrl+q
    send "\x21"
  }
}